falco:
  tty: true

  driver:
    enabled: true
    kind: modern_ebpf
    sysfsMountPath: /sys/kernel

    modernEbpf:
      leastPrivileged: true
      bufSizePreset: 4
      cpusForEachBuffer: 2
      disableIterators: false
      sysfsMount: true

    loader:
      enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  collectors:
    enabled: true

    containerEngine:
      enabled: true

      engines:
        docker:
          enabled: false

        podman:
          enabled: false

        containerd:
          enabled: false

        cri:
          enabled: true
          sockets:
            - /run/k3s/containerd/containerd.sock

        lxc:
          enabled: false

        libvirt_lxc:
          enabled: false

        bpm:
          enabled: false

    kubernetes:
      enabled: false

  metrics:
    enabled: true
    interval: 15m

    service:
      create: true
      type: ClusterIP

  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s

  grafana:
    dashboards:
      enabled: false

  falcosidekick:
    enabled: false

  responseActions:
    enabled: false

  falcoctl:
    artifact:
      install:
        enabled: true

      follow:
        enabled: false
