apiVersion: v2

name: robotek

description: >
  Helm chart for deploying the Robotek ROS 2 Jazzy mock delivery robot
  to a Kubernetes staging environment.

type: application

version: 0.2.0

appVersion: "1.0.0"

kubeVersion: ">=1.30.0-0"

home: https://github.com/iheb-mrabet/robotek-1.2

sources:
  - https://github.com/iheb-mrabet/robotek-1.2

keywords:
  - ros2
  - robotics
  - gazebo
  - kubernetes
  - gitops
  - devsecops

maintainers:
  - name: Iheb Mrabet
    url: https://github.com/iheb-mrabet