image:
  repository: ghcr.io/iheb-mrabet/robotek-1.2-runtime
  tag: main
  digest: "sha256:9f92892b7092cc9f3d6fa64b1e69a56a6261be4edf9d278b4588cb3b1506d144"
  pullPolicy: IfNotPresent

robot:
  rosDomainId: 42

podLabels:
  environment: staging

observability:
  enabled: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi

  limits:
    cpu: "2"
    memory: 4Gi

sharedMemory:
  enabled: true
  sizeLimit: 512Mi
