replicaCount: 1

image:
  repository: ghcr.io/iheb-mrabet/robotek-1.2-runtime
  tag: main
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

deployment:
  strategy:
    type: Recreate

robot:
  rosDomainId: 42

  launch:
    package: mock_robot_bringup
    file: full_simulation.launch.py

    arguments:
      gui: "false"
      use_sim_time: "true"

observability:
  enabled: true
  metricsPort: 9108

  exporter:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi

  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}

podLabels:
  app.kubernetes.io/component: robot-runtime
  app.kubernetes.io/part-of: robotek

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 500m
    memory: 1Gi

  limits:
    cpu: "2"
    memory: 4Gi

sharedMemory:
  enabled: true
  sizeLimit: 512Mi

healthProbes:
  startup:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 20
    failureThreshold: 30
    successThreshold: 1

  readiness:
    enabled: true
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 3
    successThreshold: 1

terminationGracePeriodSeconds: 30

nodeSelector: {}

tolerations: []

affinity: {}