image:
  repository: ghcr.io/iheb-mrabet/robotek-1.2-runtime
  tag: main
  digest: "sha256:1be91befdce33358cc891db9ba72dbcd7da795b29f6ac067612f1bcce79dfd2a"
  pullPolicy: IfNotPresent

robot:
  rosDomainId: 42

podLabels:
  environment: staging

observability:
  enabled: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi

  limits:
    cpu: "2"
    memory: 4Gi

sharedMemory:
  enabled: true
  sizeLimit: 512Mi
