image:
  repository: ghcr.io/iheb-mrabet/robotek-1.2-runtime
  tag: main
  digest: "sha256:a20944c21005f0b5ff1d1b089913cf566f0cad4b5d54b3d452cc6ef71a88a84a"
  pullPolicy: IfNotPresent

robot:
  rosDomainId: 42

podLabels:
  environment: staging

observability:
  enabled: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi

  limits:
    cpu: "2"
    memory: 4Gi

sharedMemory:
  enabled: true
  sizeLimit: 512Mi
