images:
  frontend:
    repository: ihebmrabet/robotek-demo-frontend
    tag: 75c033ba6d78902aa4439c6500e011857e83c779
  backend:
    repository: ihebmrabet/robotek-demo-backend
    tag: 75c033ba6d78902aa4439c6500e011857e83c779
  database:
    repository: ihebmrabet/robotek-demo-database
    tag: 75c033ba6d78902aa4439c6500e011857e83c779

imagePullPolicy: Always

frontend:
  nodePort: 30080

observability:
  grafanaInternalUrl: http://robotek-monitoring-grafana.monitoring.svc.cluster.local
  grafanaPublicUrl: ""
  prometheusPublicUrl: ""
