images:
  frontend:
    repository: ihebmrabet/robotek-demo-frontend
    tag: 7ea1491632c4362f13bcd9bcc39b2a463c9e0d59
  backend:
    repository: ihebmrabet/robotek-demo-backend
    tag: 7ea1491632c4362f13bcd9bcc39b2a463c9e0d59
  database:
    repository: ihebmrabet/robotek-demo-database
    tag: 7ea1491632c4362f13bcd9bcc39b2a463c9e0d59

imagePullPolicy: Always

frontend:
  nodePort: 30080

observability:
  grafanaInternalUrl: http://robotek-grafana.monitoring.svc.cluster.local
  grafanaPublicUrl: ""
  prometheusPublicUrl: ""
