images:
  frontend:
    repository: ihebmrabet/robotek-demo-frontend
    tag: f1fe3a4d1975429fee4174b015d1745c4a077a84
  backend:
    repository: ihebmrabet/robotek-demo-backend
    tag: f1fe3a4d1975429fee4174b015d1745c4a077a84
  database:
    repository: ihebmrabet/robotek-demo-database
    tag: f1fe3a4d1975429fee4174b015d1745c4a077a84

imagePullPolicy: Always

frontend:
  nodePort: 30080

observability:
  grafanaInternalUrl: http://robotek-grafana.monitoring.svc.cluster.local
  grafanaPublicUrl: ""
  prometheusPublicUrl: ""
