apiVersion: v1
kind: Service
metadata:
  name: robotek-demo-database
spec:
  selector:
    app: robotek-demo-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotek-demo-database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: robotek-demo-database
  template:
    metadata:
      labels:
        app: robotek-demo-database
        app.kubernetes.io/part-of: robotek-demo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: database
          image: {{ printf "%s:%s" .Values.images.database.repository .Values.images.database.tag | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: robotek-demo-database
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.database.user | quote }}, "-d", {{ .Values.database.name | quote }}]
            initialDelaySeconds: 4
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.database | nindent 12 }}
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data
            - name: database-run
              mountPath: /var/run/postgresql
            - name: database-tmp
              mountPath: /tmp
      volumes:
        - name: database-data
          emptyDir: {}
        - name: database-run
          emptyDir: {}
        - name: database-tmp
          emptyDir: {}
