apiVersion: v1
kind: Secret
metadata:
  name: robotek-demo-database
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@robotek-demo-database:5432/%s" .Values.database.user .Values.database.password .Values.database.name | quote }}
