apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robotek.fullname" . }}
  labels:
    {{- include "robotek.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: {{ .Values.deployment.strategy.type }}

  selector:
    matchLabels:
      {{- include "robotek.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "robotek.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "robotek.serviceAccountName" . }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: robotek

          image: {{ include "robotek.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - ros2
            - launch
            - {{ .Values.robot.launch.package | quote }}
            - {{ .Values.robot.launch.file | quote }}
            {{- range $name, $value := .Values.robot.launch.arguments }}
            - {{ printf "%s:=%s" $name $value | quote }}
            {{- end }}

          env:
            - name: ROS_DOMAIN_ID
              value: {{ .Values.robot.rosDomainId | quote }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.sharedMemory.enabled }}
          volumeMounts:
            - name: shared-memory
              mountPath: /dev/shm
          {{- end }}

      {{- if .Values.sharedMemory.enabled }}
      volumes:
        - name: shared-memory
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.sharedMemory.sizeLimit }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}