{{- if and .Values.observability.enabled .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "robotek.fullname" . }}-ros-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "robotek.labels" . | nindent 4 }}

spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  selector:
    matchLabels:
      {{- include "robotek.selectorLabels" . | nindent 6 }}

  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
{{- end }}